# Generated by Django 4.2.10 on 2024-02-23 20:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Название статьи')),
                ('author_name', models.CharField(max_length=70, verbose_name='Имя автора')),
                ('date_publicity', models.DateTimeField(verbose_name='Дата публикации')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 2, 23, 20, 1, 24, 890314, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Полное Описание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=70, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('PRO', 'Обработано'), ('NOT', 'Не обработано')], default='NOT', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Форма связи',
                'verbose_name_plural': 'Формы связи',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='images/birds', verbose_name='Наша Галерея')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалереи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_send', models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MinValueValidator(datetime.datetime)], verbose_name='Дата')),
                ('author_name', models.CharField(max_length=30, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(verbose_name='Текст комментария')),
                ('note', models.ForeignKey(default='Статья', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='birds.articles', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
