# Generated by Django 4.2.10 on 2024-02-23 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 20, 1, 31, 429119, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
