# Generated by Django 4.2.10 on 2024-02-24 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_alter_articles_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 7, 12, 55, 18601, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_publicity',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 7, 12, 55, 18601, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
