# Generated by Django 4.2.10 on 2024-02-25 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_alter_articles_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 1, 44, 8, 671530, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_publicity',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 1, 44, 8, 671530, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
